Repository wemixarchive/go-wemix, pull requests merged in 2024-06, with the labels that each got.

#95 merge: dev into master
  Dockerfile.wemix
  README.md
  build/checksums.txt
  build/ci.go
  cmd/geth/dbcmd.go
  cmd/geth/main.go
  cmd/geth/wemixcmd.go
  cmd/utils/cmd.go
  common/fdlimit/fdlimit_bsd.go
  common/fdlimit/fdlimit_darwin.go
  common/fdlimit/fdlimit_unix.go
  consensus/ethash/consensus.go
  console/console.go
  containers/docker/wemix/Dockerfile
  containers/docker/wemix/docker-compose.yml
  containers/docker/wemix/testdata/.rc
  containers/docker/wemix/testdata/bootnode.sh
  containers/docker/wemix/testdata/config.json
  containers/docker/wemix/testdata/deploy-governance.js
  containers/docker/wemix/testdata/genesis.json
  containers/docker/wemix/testdata/gwemix.sh
  containers/docker/wemix/testdata/keystore/account1
  containers/docker/wemix/testdata/keystore/account2
  containers/docker/wemix/testdata/keystore/account3
  containers/docker/wemix/testdata/keystore/maintenance
  containers/docker/wemix/testdata/nodekey/nodekey1
  containers/docker/wemix/testdata/nodekey/nodekey2
  containers/docker/wemix/testdata/nodekey/nodekey3
  core/block_validator.go
  core/blockchain.go
  core/blockchain_test.go
  core/chain_makers.go
  core/state_processor.go
  core/types.go
  core/types/block.go
  docs/FEEDELEGATION.md
  docs/container.md
  eth/api.go
  eth/backend.go
  eth/downloader/downloader.go
  eth/protocols/eth/handshake.go
  eth/state_accessor.go
  ethclient/ethclient_test.go
  go.mod
  internal/cmdtest/test_cmd.go
  internal/web3ext/web3ext.go
  metrics/cputime_unix.go
  node/errors.go
  p2p/netutil/toobig_windows.go
  p2p/simulations/adapters/exec.go
  params/config.go
  params/config_test.go
  params/version.go
  params/wemix_config.go
  wemix/admin.go
  wemix/miner/miner.go
  wemix/rewards_test.go
Labels: master

#99 fix: adjust boot node count
  cmd/utils/flags.go
Labels: master, hotfix

#100 fix: adjust boot node count (hotfix to dev)
  cmd/utils/flags.go
Labels: bug

#98 Make artifact for deploying gwemix
  .github/workflows/artifacts.yml
Labels: ci

#92 merge: dev into devnet
  .github/workflows/artifacts.yml
  Dockerfile.wemix
  README.md
  build/checksums.txt
  build/ci.go
  cmd/geth/dbcmd.go
  cmd/geth/main.go
  cmd/geth/wemixcmd.go
  cmd/utils/cmd.go
  cmd/utils/flags.go
  common/fdlimit/fdlimit_bsd.go
  common/fdlimit/fdlimit_darwin.go
  common/fdlimit/fdlimit_unix.go
  consensus/ethash/consensus.go
  console/console.go
  containers/docker/wemix/Dockerfile
  containers/docker/wemix/docker-compose.yml
  containers/docker/wemix/testdata/.rc
  containers/docker/wemix/testdata/bootnode.sh
  containers/docker/wemix/testdata/config.json
  containers/docker/wemix/testdata/deploy-governance.js
  containers/docker/wemix/testdata/genesis.json
  containers/docker/wemix/testdata/gwemix.sh
  containers/docker/wemix/testdata/keystore/account1
  containers/docker/wemix/testdata/keystore/account2
  containers/docker/wemix/testdata/keystore/account3
  containers/docker/wemix/testdata/keystore/maintenance
  containers/docker/wemix/testdata/nodekey/nodekey1
  containers/docker/wemix/testdata/nodekey/nodekey2
  containers/docker/wemix/testdata/nodekey/nodekey3
  core/block_validator.go
  core/blockchain.go
  core/blockchain_test.go
  core/chain_makers.go
  core/state_processor.go
  core/types.go
  core/types/block.go
  docs/FEEDELEGATION.md
  docs/container.md
  eth/api.go
  eth/backend.go
  eth/downloader/downloader.go
  eth/protocols/eth/handshake.go
  eth/state_accessor.go
  ethclient/ethclient_test.go
  go.mod
  internal/cmdtest/test_cmd.go
  internal/web3ext/web3ext.go
  metrics/cputime_unix.go
  node/errors.go
  p2p/netutil/toobig_windows.go
  p2p/simulations/adapters/exec.go
  params/config.go
  params/config_test.go
  params/version.go
  params/wemix_config.go
  wemix/admin.go
  wemix/miner/miner.go
  wemix/rewards_test.go
Labels: devnet

#108 feat: brioche configuation for devnet
  .github/workflows/devnet-ci.yml
  core/genesis.go
  params/config.go
Labels: devnet

#112 feat: brioche configuation for devnet
  core/genesis.go
  params/config.go
Labels: devnet
