Repository wemixarchive/go-wemix, pull requests merged in 2024-09, with the labels that each got.

#122 fix : remove memsize
  cmd/geth/main.go
  go.mod
  go.sum
  internal/debug/flags.go
  mobile/geth.go
Labels: enhancement

#117 feat: add eth 68 protocol
  cmd/devp2p/internal/ethtest/suite.go
  cmd/devp2p/internal/ethtest/types.go
  core/rawdb/accessors_chain.go
  eth/handler_eth.go
  eth/handler_eth_test.go
  eth/protocols/eth/broadcast.go
  eth/protocols/eth/handler.go
  eth/protocols/eth/handler_test.go
  eth/protocols/eth/handlers.go
  eth/protocols/eth/peer.go
  eth/protocols/eth/peer_test.go
  eth/protocols/eth/protocol.go
  p2p/peer.go
  p2p/protocol.go
  wemix/bind/structs.go
Labels: enhancement

#126 Feat: version patch to 9
  params/version.go
Labels: versioning

#128 ci: update devnet ci
  .github/workflows/devnet-ci.yml
Labels: devnet, ci

#130 ci: artifact and release ci script
  .github/workflows/artifacts.yml
  .github/workflows/release.yml
Labels: ci

#132 implement montblanc hard fork
  consensus/ethash/consensus.go
  miner/worker.go
  params/config.go
Labels: enhancement
