Repository wemixarchive/go-wemix, pull requests merged in 2025-03, with the labels that each got.

#144 fix: modify pn
  params/wemix_config.go
Labels: enhancement

#142 test scripts with fixed nodekey
  local-docker-env/Dockerfile.boot
  local-docker-env/Dockerfile.boot.git
  local-docker-env/Dockerfile.node
  local-docker-env/Dockerfile.node.git
  local-docker-env/README.md
  local-docker-env/gen-account.sh
  local-docker-env/gen-config.sh
  local-docker-env/gen-docker-compose-git.sh
  local-docker-env/gen-docker-compose.sh
  local-docker-env/gen-nodekey.sh
  local-docker-env/init-boot.sh
  local-docker-env/init-node.sh
  local-docker-env/local-docker-git.sh
  local-docker-env/local-docker.sh
  local-docker-env/nodekey/nodekey1
  local-docker-env/nodekey/nodekey2
  local-docker-env/nodekey/nodekey3
  local-docker-env/nodekey/nodekey4
  local-docker-env/set-nodekey.sh
  wemix/scripts/genesis-template.json
Labels: enhancement

#145 fix: version up to 0.10.10
  params/version.go
Labels: versioning

#146 merge v0.10.10 to devnet
  cmd/geth/chaincmd.go
  cmd/geth/config.go
  cmd/utils/flags.go
  consensus/ethash/consensus.go
  local-docker-env/Dockerfile.boot
  local-docker-env/Dockerfile.boot.git
  local-docker-env/Dockerfile.node
  local-docker-env/Dockerfile.node.git
  local-docker-env/README.md
  local-docker-env/gen-account.sh
  local-docker-env/gen-config.sh
  local-docker-env/gen-docker-compose-git.sh
  local-docker-env/gen-docker-compose.sh
  local-docker-env/gen-nodekey.sh
  local-docker-env/init-boot.sh
  local-docker-env/init-node.sh
  local-docker-env/local-docker-git.sh
  local-docker-env/local-docker.sh
  local-docker-env/nodekey/nodekey1
  local-docker-env/nodekey/nodekey2
  local-docker-env/nodekey/nodekey3
  local-docker-env/nodekey/nodekey4
  local-docker-env/set-nodekey.sh
  miner/worker.go
  params/config.go
  params/version.go
  params/wemix_config.go
  wemix/scripts/genesis-template.json
Labels: devnet
